app/models.py
from datetime import datetime
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from flask import current_app
from werkzeug.security import generate_password_hash, check_password_hash
from app import db, login
from flask_login import UserMixin

@login.user_loader
def load_user(id):
    return User.query.get(int(id))

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    email = db.Column(db.String(120), index=True, unique=True)
    image_file = db.Column(db.String(20), nullable=False, default='default.png')
    password_hash = db.Column(db.String(128))
    trackers = db.relationship('Tracker', backref='author', lazy='dynamic')
    last_seen = db.Column(db.DateTime, nullable=True, default=datetime.utcnow)

    def get_reset_token(self, expires_sec=1200):
        s = Serializer(current_app.config['SECRET_KEY'], expires_sec)
        return s.dumps({'user_id': self.id}).decode('utf-8')

    @staticmethod
    def verify_reset_token(token):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            user_id = s.loads(token)['user_id']
        except:
            return None
        return User.query.get(user_id)


    def __repr__(self):
        return f"User('{self.username}', '{self.email}', '{self.image_file}, '{self.last_seen}')"
    
    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)
    
class Tracker(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    project = db.Column(db.String(60), nullable=False)
    subject = db.Column(db.String(140), nullable=False)
    content = db.Column(db.String(300), nullable=False)
    priority = db.Column(db.String(16), nullable=False)
    progress = db.Column(db.String(16), nullable=False)
    date_created = db.Column(db.DateTime, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    def __repr__(self):
        return f"Bug('{self.id}', '{self.project}', {self.subject}', '{self.content}', '{self.priority}', '{self.progress}', '{self.date_created}')"

app/main/forms.py
from flask import request_started
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, SelectField
from wtforms.validators import ValidationError, DataRequired, Length


class TrackerForm(FlaskForm):
    # Each field is given a label as a first argument
    project = StringField('Project', validators=[DataRequired()])
    subject = StringField('Subject', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    priority = SelectField('Priority', choices=[('high', 'High'), ('moderate', 'Moderate'), ('low', 'Low')])
    progress = SelectField('Progress', choices=[('completed', 'Completed'), 
                            ('in-progress', 'In Progress'), ('not-started', 'Not Started')])
    submit = SubmitField('Submit')

app/__init__.py
import os
import logging
from logging.handlers import SMTPHandler, RotatingFileHandler
from flask import Flask, request, current_app
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager
from flask_mail import Mail
from config import Config

db = SQLAlchemy()
migrate = Migrate()
login = LoginManager()
login.login_view = 'auth.login'  # flask-login needs to know view function that handles *logins*(endpoint)
login.login_message = '' # Work around to get custom messages, look for flash messages in routes
mail = Mail()


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(Config)

    db.init_app(app)
    migrate.init_app(app, db)
    login.init_app(app)
    mail.init_app(app)

    from app.errors import bp as errors_bp
    app.register_blueprint(errors_bp)

    from app.auth import bp as auth_bp
    app.register_blueprint(auth_bp, url_prefix='/auth')

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    
    if not app.debug:
        if app.config['MAIL_SERVER']:    # Email errors to Admin
            auth = None
            if app.config['MAIL_USERNAME'] or app.config['MAIL_PASSWORD']:
                auth = (app.config['MAIL_USERNAME'], app.config['MAIL_PASSWORD'])
            secure = None
            if app.config['MAIL_USE_TLS']:
                secure = ()
            mail_handler = SMTPHandler(
                mailhost=(app.config['MAIL_SERVER'], app.config['MAIL_PORT']),
                fromaddr='no-reply@' + app.config['MAIL_SERVER'],
                toaddrs=app.config['ADMINS'], subject='Chikinita Bug Failure',
                credentials=auth, secure=secure)
            mail_handler.setLevel(logging.ERROR)
            app.logger.addHandler(mail_handler)

        if not os.path.exists('logs'):
            os.mkdir('logs')
        file_handler = RotatingFileHandler('logs/bug_tracker.log', maxBytes=10240,
                                            backupCount=10)
        file_handler.setFormatter(logging.Formatter(
            '%(asctime)s %(levelname)s: %(message)s [in %(pathname)s:%(lineno)d]'))                                        
        file_handler.setLevel(logging.INFO)
        app.logger.addHandler(file_handler)

        app.logger.setLevel(logging.INFO)
        app.logger.info('Bug Tracker startup')
    return app

app/main/__init__.py
from flask import Blueprint
# Creating an instance of this blueprint, main is the name of this blueprint
bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from datetime import datetime
from flask import render_template, flash, redirect, url_for, request, current_app, abort
from flask_login import current_user, login_required
from app import db
from app.main.forms import TrackerForm
from app.models import User, Tracker
from app.main import bp


@bp.before_request
def before_request():
    if current_user.is_authenticated:
        current_user.last_seen = datetime.utcnow()
        db.session.commit()

@bp.route("/")
@bp.route("/index")
@login_required
def index():
    track = Tracker.query.all()
    return render_template('index.html', track=track)



@bp.route("/bug/new", methods=['GET', 'POST'])
@login_required
def new_bug():
    form = TrackerForm()
    if form.validate_on_submit():
        track = Tracker(project=form.project.data, subject=form.subject.data, content=form.content.data, 
                        priority=form.priority.data, progress=form.progress.data, author=current_user)
        db.session.add(track)
        db.session.commit()
        flash('Your new issue is being tracked!', 'success')
        return redirect(url_for('main.index'))
    return render_template('new_bug.html', title='New Bug Report', form=form, legend='New Bug')

@bp.route("/bug/<int:track_id>")
def bug(track_id):
    bug = Tracker.query.get_or_404(track_id)
    return render_template('bug.html', title=bug.subject, bug=bug)

@bp.route("/bug/<int:track_id>/update", methods=['GET', 'POST'])
def update_bug(track_id):
    bug = Tracker.query.get_or_404(track_id)
    if bug.author != current_user:
        abort(403)
    form = TrackerForm()
    if form.validate_on_submit():
        bug.project = form.project.data
        bug.subject = form.subject.data
        bug.content = form.content.data
        bug.priority = form.priority.data
        bug.progress = form.progress.data
        db.session.commit()
        flash('Your bug has been updated!', 'success')
        return redirect(url_for('main.index', track_id=track_id))
    elif request.method == 'GET':
        form.project.data = bug.project
        form.subject.data = bug.subject
        form.content.data = bug.content
        form.priority.data = bug.priority
        form.progress.data = bug.progress
    return render_template('new_bug.html', title='Update Bug', form=form, legend='Update Bug')

@bp.route("/bug/<int:track_id>/delete", methods=['POST']) # note? must be bug?
def delete_bug(track_id):
    bug = Tracker.query.get_or_404(track_id)
    if bug.author != current_user:
        abort(403)
    db.session.delete(bug)
    db.session.commit()
    flash('Your bug has been deleted!', 'success')
    return redirect(url_for('main.index'))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Chikinita.com</title>

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css2?family=Caveat&family=Open+Sans+Condensed:ital@1&display=swap" rel="stylesheet">
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" 
  <!-- Custom styles for this template -->
  <link href="{{ url_for('static', filename='main.css') }}" rel="stylesheet">
</head>
<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark_purple fixed-top">
    <div class="container">
      <a class="navbar-brand" href="{{ url_for('main.index') }}">Chikinita.com</a>

        {% if current_user.is_anonymous %}
       
        {% else %}
        <!-- Dropdown -->
          <div class="dropdown">

            <button type="button" class="btn dropdown-toggle btn-sm btn-outline-dark" data-toggle="dropdown">
            <img class="rounded-circle small-image img-fluid"
            src="{{ url_for('static', filename='profile_pics/' + current_user.image_file) }}">
            <span class="sr-only">(current)</span></button>
          
          <div class="dropdown-menu dropdown-menu-right">
            <div class="dropdown-item"><small class="text-muted">@</small>{{ current_user.username }}</div>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{{ url_for('main.index') }}">Home</a>
            <a class="dropdown-item" href="{{ url_for('auth.user', username=current_user) }}">Account</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{{ url_for('auth.logout') }}">Logout <span class="sr-only">(current)</span></a>   
            
          </div>
          </div>
        {% endif %}  
            </ul>   
      </nav>
        

  <!-- Page Content -->
  <main role="main" class="container-xs"></main>
    
  <!-- Python Messages -->
  
<div class="container">
      {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class="container-fluid col-sm-6 col-sm-offset-1">
                <div class="alert alert-{{ category }} alert-dismissible fade show" 
                role="alert">
                <span>{{ message }}</span>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
                </div>
                </div>
            {% endfor %}
        {% endif %}
      {% endwith %}

<!-- Other templates get inserted here-->

  {% block content %}
      
  {% endblock %}
</div>
    
        <!-- /#wrapper -->
    
      <!-- Bootstrap core JavaScript -->
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    

      <!-- Menu Toggle Script -->
      <script>
        $("#menu-toggle").click(function(e) {e.preventDefault();
          $("#wrapper").toggleClass("toggled");
        });
      </script>
    </body>
    
    </html>

app/templates/bug.html
{% extends "base.html" %}
{% block content %}
    <article class="media content-section">
        <div class="media-body">
            <div class="article-metadata">
                <p class="article label"><small class="text-muted">Project: </small>{{ bug.project.title() }}</p>
                <small class="text-muted">Subject:</small>
                <h5 class="article-content">{{ bug.subject.title() }}</h5>
                <small class="text-muted">Date Created: {{ bug.date_created.strftime('%Y-%m-%d') }}</small><hr>
                    <p class="article-label">
                    <small class="text-muted">Description:</small><br>
                    {{ bug.content }}</p>
                    <p class="article-content">
                        <small class="text-muted">Priority:</small> {{ bug.priority }}</p>
                    </p>
                        <small class="text-muted">Progress:</small>  {{ bug.progress }}</p>
                </div>
                <div>
                    <a class="btn btn-info btn-sm mt-1 mb-1" href="{{ url_for('main.update_bug', track_id=bug.id) }}">Update</a>
                    <button type="button", class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
                </div>
    </article>
    <!-- Modal -->
         <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
            <div class="modal-dialog", role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="deleteModalLabel">Delete Note?</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <form action="{{ url_for('main.delete_bug', track_id=bug.id) }}" method="POST">
                            <input class="btn btn-danger" type="submit" value="Delete">
                        </form>
                    </div>
                </div>
            </div>
         </div>
                
{% endblock content %}

app/templates/index.html
{% extends "base.html" %} 
{% block content %}

<div class="container">
<div>
  <h3>Bugs
  <a class="btn btn-info btn-sm float-right mt-1 mb-1" href="{{ url_for('main.new_bug') }}">New Bug</a></h3>
</div>
  <table class="table table-hover mt-3">
    <thead class="table table-secondary">
        <tr>
          <th>ID</th>
          <th>Project</th>
          <th>Subject</th>
          <th>Created</th>
          <th>Priority</th>
          <th>Progress</th>
        </tr>
      </thead>
        {% for t in track %}
          {% if t.author == current_user %}
          <tbody>
            <tr>
              <td>{{ t.id }}</td>
              <td>{{ t.project.title() }}</td>
              <td>
                <a class="article-title" href="{{ url_for('main.bug', track_id=t.id) }}">
                {{ t.subject.title() }}</a>
              </td>
              <td>
                <small class="text-muted">{{ t.date_created.strftime('%Y-%m-%d') }}</small>
              </td>
              <td>{{ t.priority }}</td>
              <td>{{ t.progress }}</td>
              
            {% endif %}

            {% endfor %}
    </tbody>
  </table>
</div>
{% endblock content %}

app/templates/login.html
{% extends "base.html"%}
{% block content %}
<div class="container">
<div class="row mb-3">
<div class="col-sm-6 order-12 order-sm-1 text-muted">

Chikinita.com offers a free, open source bug tracking application for your development needs.
Currently it does not support collaboration.</p>
<ul>
<li><a href="mailto:chikinita@yahoo.com" target="_blank" rel="noopener noreferrer">Support</a></li>
<li><a href="https://gitlab.com/miguelpengson/flask_bug_tracker" target="_blank" rel="noopener noreferrer">GitLab</a></li>
</ul>
</div>
<div class="col-sm-6 order-1 order-sm-12 new-sessions-forms-container">
<div class="text-center content-section">
<form action="" method="POST" novalidate>
    {{ form.hidden_tag() }}
    <div class="form-group">
        {{ form.username.label }}<br>
        {{ form.username }}<br>
        {% for error in form.username.errors %}
        <span style="color: red;">{{ error }}</span>
        {% endfor %}
    </div>
    <div class="form-group">
        {{ form.password.label }}<br>
        {{ form.password }}<br>
        {% for error in form.password.errors %}
        <span style="color: red;">{{ error }}</span>
        {% endfor %}
    </div>
    <div class="form-group float">
    <small>{{ form.remember_me() }} {{ form.remember_me.label }}&emsp;
        <a href="{{ url_for('auth.reset_request') }}">Forgot Password?</a>
    </small>
    </div>
    <div class="form-group submit-container">
    {{ form.submit(class="btn btn-sm btn-success") }}
    </div>
    
</form>
    <small>New User?    <a href="{{ url_for('auth.register') }}"> Please Register!</a></small>
</div>
</div>
</div>
</div>
{% endblock content%}

app/templates/new_bug.html
{% extends "base.html" %}
{% block content %}
<div class="content-section">
    <form method ="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            <div class="form-group">
                {{ form.project.label(class="form-control-label") }}
                {{ form.project(class="form-control form-control-lg") }}
            </div>
            <div class="form-group">
                {{ form.subject.label(class="form-control-label") }}
                {{ form.subject(class="form-control form-control-lg") }}
            </div>
            <div class="form-group">
                {{ form.content.label(class="form-control-label") }}
                {{ form.content(class="form-control form-control-textarea") }}
            </div>
            <div class="form-group">
                {{ form.priority.label(class="form-control-label") }}
                {{ form.priority(class="form-control form-control-textarea") }}
            </div>
            <div class="form-group">
                {{ form.progress.label(class="form-control-label") }}
                {{ form.progress(class="form-control form-control-textarea") }}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-info")}}
        </div>
    </form>
</div>




{% endblock content %}

app/templates/register.html
{% extends "base.html" %}
{% block content %}
<div class="content-section">
    <h1>Register</h1>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <p>
            {{ form.username.label }}<br>
            {{ form.username(size=32) }}<br>
            {% for error in form.username.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.email.label }}<br>
            {{ form.email(size=32) }}<br>
            {% for error in form.email.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}<br>
            {% for error in form.password.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password2.label }}<br>
            {{ form.password2(size=32) }}<br>
            {% for error in form.password2.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.submit(class="btn btn-info") }}</p>
    </form>
</div>
{% endblock content %}

app/templates/reset_request.html
{% extends "base.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Reset Password</legend>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-md is-invalid")}}
                    <div class="invalid-feedback">
                        {% for error in errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control form-control-md") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-info")}}
        </div>
    </form>
</div>

{% endblock content %}

app/templates/reset_token.html
{% extends "base.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Reset Password</legend>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-md is-invalid")}}
                    <div class="invalid-feedback">
                        {% for error in errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password(class="form-control form-control-md") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.confirm_password.label(class="form-control-label") }}
                {% if form.confirm_password.errors %}
                    {{ form.confirm_password(class="form-control form-control-md is-invalid")}}
                    <div class="invalid-feedback">
                        {% for error in errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.confirm_password(class="form-control form-control-md") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info")}}
        </div>
    </form>
</div>

{% endblock content %}

app/templates/user.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section">
        <div class="media">
            <img class="rounded-circle account-img" src="{{ image_file }}">
        
            <div class="media-body">
                <h2 class="account-heading">{{ current_user.username }}</h2>
                <p class="text-secondary">{{ current_user.email }}</p>
            </div>
        </div>
        
            <form method="POST" action="" enctype="multipart/form-data">
                {{ form.hidden_tag() }}
                <!-- Username -->
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Account Info</legend>
                    <div class="form-group">
                        {{ form.username.label(class="form-control-label") }}

                        {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>

                        {% else %}
                            {{ form.username(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <!-- Email -->
                    <div class="form-group">
                        {{ form.email.label(class="form-control-label") }}

                        {% if form.email.errors %}
                            {{ form.email(class="form-control form-control-lg is-invalid")}}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>

                        {% else%}
                            {{ form.email(class="form-control form-control-lg ")}}
                        {% endif %}
                    </div>
                    <!-- Profile Picture -->
                    <div class="form-group">
                        {{ form.picture.label() }}
                        {{ form.picture(class="form-control-file") }}
                        {% if form.picture.errors %}
                            {% for error in form.picture.errors %}
                                <span class="text-danger">{{ error }}</span>
                            {% endfor %}
                        {% endif %}
                    </div>
                </fieldset>
                <div class="form-group">
                    {{ form.submit(class="btn btn-info") }}
                </div>
            </form>   
    </div>

{% endblock content %}